version: '3.1'
services:
  stats-server:
    build: ./stat/stat-server
    image: stat-server
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStat
      - DB_HOST=stats-db
      - DB_PORT=5432
      - STAT_DB_NAME=ewmStat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db-container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmStat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmService
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewmService
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=ewmService
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root